---
- name: This is a demo playbook
  hosts: all
  become: true
  tasks: 
  - name: install httpd and firewalld
    dnf: 
      name: 
        - httpd
        - firewalld
      state: present
  - name: adding content
    copy: 
      content: "Hello World from Automation Controller\n"
      dest: /var/www/html/index.html
  - name: starting and enabling httpd and firewalld
    service: 
      name: "{{ item }}"
      state: started
      enabled: true
    loop: 
    - httpd
    - firewalld
  - name: adding http in firewalld
    ansible.posix.firewalld: 
      service: http
      immediate: true
      permanent: true
      state: enabled
